### Site Settings ###
title               : Yvonne27Jin
description         : >-
                      Computational Social Scientist,
                      love good visuals, on-point analysis and
                      enchanting storytelling.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Yvonne27Jin/Yvonne27Jin.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
#  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Yvonne JIN
  image             : "./profile_photo.jpeg" 
#  behance           : your_username
# dribbble          : your_username
  email             : yvonne27hku@gmail.com
#  facebook          : your_username
  github            : Yvonne27Jin
# gitlab            : your_username
  instagram         : yvonne27jin
# kaggle            : your_username
  linkedin          : yvonne-yaqi-jin-78468b180
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : yvonnejin2
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
#  elements:                                             # For Documentation Only
#    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: yvonne27jin                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
#  - scope:                                              # For Documentation Only
#      path: ""                                          # For Documentation Only
#      type: "elements"                                  # For Documentation Only
#    values:                                             # For Documentation Only
#      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
